task:
  name: ubuntu-18.04
  container:
    matrix:
      image: seladb/ubuntu1804:latest
  get_code_script: git clone https://github.com/seladb/PcapPlusPlus.git
  configure_script:
    - cd PcapPlusPlus
    - ./configure-linux.sh --default
  build_script: 
    - cd PcapPlusPlus
    - make all
  package_script:
    - pwd
    - ../PcapPlusPlus-Deploy/linux-mac/deploy-linux-mac.sh
    
