task:
  name: linux
  env:
    matrix:
      - IMAGE_NAME: ubuntu1804
        OS_VER: ubuntu-18.04
  container:
    image: seladb/${IMAGE_NAME}:latest
  get_code_script: git clone https://github.com/seladb/PcapPlusPlus.git
  configure_script:
    - cd PcapPlusPlus
    - ./configure-linux.sh --default
  build_script: 
    - cd PcapPlusPlus
    - make all
  package_script:
    - linux-mac/deploy-linux.sh
  package_artifacts:
    path: "package/*"
