task:
  name: package-linux
  env:
    matrix:
      - IMAGE_NAME: ubuntu1404
        OS_VER: ubuntu-14.04
      - IMAGE_NAME: ubuntu1604
        OS_VER: ubuntu-16.04
      - IMAGE_NAME: ubuntu1804
        OS_VER: ubuntu-18.04
      - IMAGE_NAME: centos7
        OS_VER: centos-7
      - IMAGE_NAME: fedora29
        OS_VER: fedora-29
  container:
    image: seladb/${IMAGE_NAME}:latest
  get_code_script: git clone https://github.com/seladb/PcapPlusPlus.git
  configure_script:
    - cd PcapPlusPlus
    - ./configure-linux.sh --default
  build_script: 
    - cd PcapPlusPlus
    - make all
  test_script:
    - cd PcapPlusPlus/Tests/Packet++Test && Bin/Packet++Test
    - cd ../Pcap++Test && sudo Bin/Pcap++Test -n
  package_script:
    - linux-mac/deploy-linux.sh
  deploy_package_artifacts:
    path: "package/*"

task:
  name: package-source
  container:
    image: seladb/ubuntu1804:latest  
  get_code_script: git clone https://github.com/seladb/PcapPlusPlus.git
  install_script:
    - apt-get -y install rsync
  package_script:
    - source-linux/deploy-source.sh
  deploy_package_artifacts:
    path: "package/*"

  task:
    name: package-freebsd
    freebsd_instance:
      matrix:
        image_family: freebsd-11-2
        image_family: freebsd-12-0
    install_script: pkg install -y git libpcap bash gsed gmake        
    get_code_script: git clone https://github.com/seladb/PcapPlusPlus.git
    configure_script:
      - cd PcapPlusPlus
      - ./configure-freebsd.sh --default
    build_script:
      - cd PcapPlusPlus
      - gmake all
    test_script:
      - cd PcapPlusPlus/Tests/Packet++Test && Bin/Packet++Test
      - cd ../Pcap++Test && sudo Bin/Pcap++Test -n
    package_script:
      - linux-mac/deploy-freebsd.sh
    deploy_package_artifacts:
      path: "package/*"