task:
  name: package-linux
  env:
    matrix:
      - IMAGE_NAME: ubuntu1404
        OS_VER: ubuntu-14.04
      - IMAGE_NAME: ubuntu1604
        OS_VER: ubuntu-16.04
      - IMAGE_NAME: ubuntu1804
        OS_VER: ubuntu-18.04
      - IMAGE_NAME: centos7
        OS_VER: centos-7
      - IMAGE_NAME: fedora29
        OS_VER: fedora-29
  container:
    image: seladb/${IMAGE_NAME}:latest
  get_code_script: git clone https://github.com/seladb/PcapPlusPlus.git
  configure_script:
    - cd PcapPlusPlus
    - ./configure-linux.sh --default
  build_script: 
    - cd PcapPlusPlus
    - make all
  package_script:
    - linux-mac/deploy-linux.sh
  deploy_package_artifacts:
    path: "package/*"

task:
  name: package-macos
  osx_instance:
    matrix:
      image: mojave-xcode-11.1
  get_code_script: git clone https://github.com/seladb/PcapPlusPlus.git
  configure_script:
    - cd PcapPlusPlus
    - ./configure-mac_os_x.sh
  build_script: 
    - cd PcapPlusPlus
    - make all
  package_script:
    - linux-mac/deploy-mac.sh
  deploy_package_artifacts:
    path: "package/*"