sudo: required
language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode7.3
    - os: osx
      compiler: clang
      osx_image: xcode8.3
    - os: osx
      compiler: clang
      osx_image: xcode9.2
    - os: osx
      compiler: clang
      osx_image: xcode9.4
    - os: osx
      compiler: clang
      osx_image: xcode10.1
    - os: osx
      compiler: clang
      osx_image: xcode10.3
    - os: osx
      compiler: clang
      osx_image: xcode11
    - os: osx
      compiler: clang
      osx_image: xcode11.2

before_install:
  - git clone https://github.com/seladb/PcapPlusPlus.git && cd PcapPlusPlus

before_script:
  - ./configure-mac_os_x.sh
  
script:
  - make all
  - cd Tests/Packet++Test && Bin/Packet++Test
  - cd ../Pcap++Test && sudo Bin/Pcap++Test -n
  - cd ../../../ && g++ -dumpversion > gcc.version

after_success:
  - linux-mac/deploy-mac.sh
