sudo: required
language: cpp
services:
  - docker

matrix:
  include:
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1404

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       docker pull seladb/$DOCKER_IMAGE:latest;
       docker run -itd --name $DOCKER_IMAGE -v $(pwd):/PcapPlusPlus seladb/$DOCKER_IMAGE;
    fi

before_script:
  - cd .. && git clone https://github.com/seladb/PcapPlusPlus.git && cd PcapPlusPlus
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure-mac_os_x.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && ./configure-linux.sh --default"; fi
  - if [[ ! -z $DPDK_DIR ]]; then docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && ./configure-linux.sh --dpdk --dpdk-home /$DPDK_DIR"; fi
  - if [[ ! -z $PF_RING ]]; then docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && ./configure-linux.sh --pf-ring --pf-ring-home /PF_RING"; fi
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       make all;
       cd Tests/Packet++Test && Bin/Packet++Test;
       cd ../Pcap++Test && sudo Bin/Pcap++Test -n;
    else
       docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && make all";
       docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus/Tests/Packet++Test && Bin/Packet++Test";
       docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus/Tests/Pcap++Test && Bin/Pcap++Test -n -k 0";
    fi
